#!/bin/bash
WORDLE_DIR="$(dirname $0)"
ls
if [[ $LANG =~ en ]] || [ ${LANG:-zzz} = 'zzz' ]
then
	python "${WORDLE_DIR}"/main.py "${WORDLE_DIR}"/english
elif [[ $LANG =~ de ]]
then
	python "${WORDLE_DIR}"/main.py "${WORDLE_DIR}"/german
fi


